services:
  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ${WORK_DIR:-/home/troll/sites/llm}:/llama.cpp/models
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    container_name: llm-container

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://llm:5555
      - PORT=5000
    depends_on:
      - llm