services:
  llm:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ${WORK_DIR:-/home/troll/sites/llm}:/llama.cpp/models
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    container_name: llm-container
    restart: unless-stopped
    environment:
      - JWT_SECRET=${JWT_SECRET}

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5555
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - ./frontend/.env.local
    depends_on:
      llm:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    container_name: nextjs-container
    restart: unless-stopped
